fluentd-elasticsearch:
  elasticsearch:
    hosts:
      - elastic.ops.elastisys-ck8s.elastisys.se
    scheme: "https"
    auth:
      enabled: true
      username: fluentd
      password: ""
  secret:
    - name: OUTPUT_PASSWORD
      secret_name: elasticsearch-password
      secret_key: password
